// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/reset-and-seed': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reset-and-seed.post').default>>>>
    }
    '/api/v1/auth/email/confirm': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/auth/email/confirm.post').default>>>>
    }
    '/api/v1/auth/password/reset': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/auth/password/reset.put').default>>>>
    }
    '/api/v1/auth/password/reset/request': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/auth/password/reset/request.post').default>>>>
    }
    '/api/v1/auth/signin': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/auth/signin.post').default>>>>
    }
    '/api/v1/auth/signout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/auth/signout.post').default>>>>
    }
    '/api/v1/auth/signup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/auth/signup.post').default>>>>
    }
    '/api/v1/permissions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/permissions/index.get').default>>>>
    }
    '/api/v1/roles/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/roles/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/roles/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/roles/[id].put').default>>>>
    }
    '/api/v1/roles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/roles/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/roles/index.post').default>>>>
    }
    '/api/v1/user/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/user/[id].get').default>>>>
    }
    '/api/v1/user': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/user/index.get').default>>>>
    }
    '/api/v1/user/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/user/profile.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/user/profile.put').default>>>>
    }
    '/api/v1/users/:userId/roles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/users/[userId]/roles.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/users/[userId]/roles.put').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/api/_auth/session': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.get').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}